### ISSUE TITLE
Search bar does not accept spaces

### ISSUE THREAD

**Issue by SabrinaHerrero** [ccmmaa/idb#128]
Example: results for "corpus" are not the same as "corpus christi"

**Comment by ChiaHuaLu** [comment]
Fixed. When the "Search" button is clicked, it go to musepy.me/search?search+terms+with+plus+signs+instead+of+spaces,
On the Search page, the plus signed query is passed to the api. 
The query term is converted back into space-separated terms and placed into the search field so that users can edit it.
